name: dink-bot          # you can call it whatever you like
on:
  schedule:
    - cron:  '*/30 * * * *'      # daily 08:00 UTC
  workflow_dispatch:          # adds the “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python bot.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit state
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.email "bot@users.noreply.github.com"
            git config user.name "Dink‑Bot"
            git add state.json
            git commit -m "Update state"
            git push
          fi