# name: dink-bot          
#on:
#  schedule:
#    - cron:  '*/30 * * * *'      
#  workflow_dispatch:          

#jobs:
#  run:
#    runs-on: ubuntu-latest

#    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python bot.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

      - name: Commit state
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.email "bot@users.noreply.github.com"
            git config user.name "Dink‑Bot"
            git add state.json
            git commit -m "Update state"
            git push
          fi
